spacegraphcats/catlas.py
spacegraphcats/minhash.py

Switch to using MinHash from khmer

---

.travis.yml
README.md

With travis we can actually test python 2 and 3 in parallel.

Use travis

---

dump_catlas.py
gimme-dbg-nodes.py
gimme-reads.py
requirements.txt
search-catlas-mh.py
search-dbg.py
search-for-domgraph-nodes-multi.py
search-for-domgraph-nodes.py
spacegraphcats/catlas.py
spacegraphcats/color-domgraph.py
spacegraphcats/graph.py
spacegraphcats/search-catlas-levels.py
walk-dbg.py

This adds two new scripts, `gimme-dbg-nodes.py` and `gimme-reads.py`, that respectively extract the cDBG minhashes for a given search & the sequences containing those minhashes.  This is important functionality for validating the search, as well as something that people will actually want to do.
(Not yet ready for merge!)

scripts to extract reads that contributed to parts of the graph

---

search-dbg.py

On calculating sensitivity and specificity

Error on search-dbg.py 

---

gimme-reads.py
spacegraphcats/test_cmd_line.py
walk-dbg.py

Output MinHash sketches as we go, rather than keeping them in memory.

Output MinHash sketches as we go, rather than keeping them in memory.

---

search-for-domgraph-nodes.py
spacegraphcats/catlas.py

There were a lot of places in the code where we were traversing the catlas in a really inefficient manner and covering the same nodes over and over.  This is now fixed and we should get some speedup, especially on large data sets.

Gross inefficiencies

---

spacegraphcats/rdomset.py
spacegraphcats/test_domset.py
spacegraphcats/test_graph.py

This addresses issue #43: the TFGraph class and the code to compute dominating sets are now tested with random graph instances and some small hand-crafted cases. The dominating set code contains more comments, however, without knowledge of the underlying algorithms/data-structures even these will probably not help.

Graph tests

---

spacegraphcats/rdomset.py

Fixes https://github.com/spacegraphcats/spacegraphcats/issues/50

Remove the need for a bunch of dictionary lookups and make all in_neighbors calls use an explicit r

---

ctb/Makefile
ctb/make-catlas-minhashes.py
ctb/search-catlas-with-minhash.py
spacegraphcats/catlas.py
spacegraphcats/walk_dbg.py

Many small `ctb/` fixes and cleanup and documentation and flexibility.
Note: removes cProfile output from catlas building.
Ready for merge @domoritz.

[MRG] A bunch of miscellaneous cleanup

---

doc/sourmash-commands.md
search/frontier_search.py
search/make_catlas_minhashes.py
search/search_catlas_with_minhash.py

do not output empty minhashes

---

Makefile
search/analyze_profile.py
search/frontier_search.py
search/frontier_search_batch.py
search/make_catlas_minhashes.py
search/memoize.py
search/search_catlas_with_minhash.py

Use memoization to speed up frontier search.

---

Makefile
search/frontier_search.py
search/frontier_search_batch.py
search/make_catlas_minhashes.py
search/search_catlas_with_minhash.py
spacegraphcats/catlas.py
spacegraphcats/walk_dbg.py

The files in the project directories now have the same names regardless of the project name.  Fixes #89

Standard naming conventions

---

search/frontier_search.py
search/search_catlas_with_minhash.py

requires new install of sourmash:
```
pip install -U https://github.com/dib-lab/sourmash/archive/spacegraphcats.zip
```

rename MinHash.containment to MinHash.contained_by

---

search/make_catlas_minhashes.py
spacegraphcats/walk_dbg.py

necessary for #104, might fix some problems we've seen with podar.

add high degree node hashes to contigs file

---

.gitignore
.travis.yml
Makefile
scripts/15genome-search.log
scripts/acidio-search.log
scripts/test-search-changes.sh

If so, merge with care as this will require rebuilding some big files.

Test basic workflows

---

Makefile
search/frontier_search.py

add --fullstats option to frontier search; provide more output

---

.gitignore
spacegraphcats/catlas.py

The checkpoint saves are threaded and zipped (re #115).  The loads are now compatible with disconnected graphs (re #112).

Better checkpoint saving and loading

---

search/make_catlas_minhashes.py

If so, merge with care as this will require rebuilding some big files.

scaled_to_max_hash not in sourmash_lib any more

---

spacegraphcats/rdomset.py

Removes a sanity check that is very expensive for upper levels of the catlas.  also did a little bit of PEP8 compliance so I don't have to look at the red squiggles in Atom ;)

remove expensive check

---

requirements.txt
search/make_catlas_minhashes.py
search/test_workflow.py
spacegraphcats/test_components.py
spacegraphcats/test_graph.py
spacegraphcats/walk_dbg.py

If so, merge with care as this will require rebuilding some big files.

[MRG] Update the requirements.txt for khmer release, add numpy.

---

.travis.yml
search/frontier_search.py
search/frontier_search_batch.py
spacegraphcats/build_contracted_dbg.py

[MRG] add -k option to frontier search in case signature has multiple ksizes

---

Makefile
search/extract_contigs_by_frontier.py
search/extract_reads_by_frontier.py
search/frontier_search_batch.py
search/search_utils.py

Adds `--no-remove-empty` and `--boost-frontier` options.

[MRG] add --no-remove-empty to extract contigs by frontier

---

Makefile
search/label_cdbg.py
search/test_workflow.py
spacegraphcats/walk_dbg.py

khmer master has moved on, and some of the interfaces have changed; this PR updates to using the interfaces from the latest khmer master.
Note, requires https://github.com/dib-lab/khmer/pull/1808, which is now in khmer/spacegraphcats branch.

[MRG] Update to using latest khmer master.

---

Makefile
search/extract_reads_by_frontier.py
spacegraphcats/gxt_to_gml.py
spacegraphcats/walk_dbg.py

Also, put in visual warnings when this happens again.
Also, add `gxt_to_gml.py`
If so, merge with care as this will require rebuilding some big files.

Fix yet another inclusion problem, this time caused by a bad cDBG calculation.

---

search/extract_reads_by_frontier.py

Ready to merge when tests pass!

[MRG] fix minhash downsample issue on extract_reads

---

README.md

zenodo DOI to readme

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
conf/Snakefile

This PR does not change the contracted DBG or catlas formats.

fix make_bgzf rule & add tests for it

---

conf/Snakefile
conf/run
spacegraphcats/search/extract_nodes_by_query.py

e.g. `conf/run dory-test extract_contigs extract_reads` will build, search, extract contigs, and extract reads. Previously this would have had to be two commands, `conf/run dory-test extract_contigs; conf/run dory-test extract_reads`.

[MRG] allow multiple targets with conf/run

---

doc/installing-spacegraphcats.md
doc/running-spacegraphcats.md

[new install docs](https://github.com/spacegraphcats/spacegraphcats/blob/update/docs/doc/installing-spacegraphcats.md)
[revised run docs](https://github.com/spacegraphcats/spacegraphcats/blob/update/docs/doc/running-spacegraphcats.md)

[WIP] split "install" and "run" docs; update run docs.

---

LICENSE
setup.py

Ready for review and merge, @domoritz @bdsullivan

[MRG] add LICENSE, UC/UW/NCState copyright; update package info a bit

---

spacegraphcats/cdbg/bcalm_to_gxt.py
spacegraphcats/search/extract_contigs.py
spacegraphcats/search/extract_reads.py

Friendly helpful changes that make my life easier.

[MRG] fix gz output from extract_reads/contigs, and output diagnostic signatures in bcalm_to_Gxt

---

.travis.yml
spacegraphcats/search/estimate_query_abundance.py
spacegraphcats/search/test_workflow.py

This can be used to look at the distribution of abundances of the query genomes for any given experiment.

[MRG] add script to calculate the abundances of queries in the cDBG

---

spacegraphcats/search/extract_nodes_by_query.py
spacegraphcats/search/index.py

**Please note** if this PR requires a rebuild of catlas or other big files.

[MRG] fix unclear errors from empty query, or no queries at all

---

conf/Snakefile
conf/hu-s1.json
scripts/benchmark_1_rdomset.py
scripts/benchmark_2_index.py
scripts/benchmark_3_query.py
scripts/kmer-bait-sequences.py
spacegraphcats/catlas/catlas.py
spacegraphcats/index/index_contigs_by_kmer.py
spacegraphcats/search/__init__.py
spacegraphcats/search/catlas_info.py
spacegraphcats/search/extract_nodes_by_query.py

**Please note** if this PR requires a rebuild of catlas or other big files.

[WIP] scripts that isolate interesting algorithms for benchmarking purposes

---

conf/run
setup.py

Allow `run` script to find `yaml` configfiles (cc @ctb)

Enable yaml config

---

spacegraphcats/search/extract_reads.py
spacegraphcats/search/search_utils.py
spacegraphcats/utils/make_bgzf.py

Note: this does not change the output sequence content, but does change their format.
tested on https://github.com/spacegraphcats/spacegraphcats-twofoo-example.

Output FASTQ if input reads are FASTQ

---

spacegraphcats/catlas/catlas.py
spacegraphcats/search/estimate_query_abundance.py
spacegraphcats/search/evaluate_overhead.py
spacegraphcats/search/extract_contigs.py
spacegraphcats/search/extract_contigs_cdbg.py
spacegraphcats/search/extract_reads.py
spacegraphcats/search/query_by_sequence.py
spacegraphcats/utils/logging.py

Goal: start differentiating between notifications, results, errors, and debugging output.

swipe a bunch of logging functions from sourmash

---

spacegraphcats/search/extract_nodes_by_shadow_ratio.py
spacegraphcats/search/test_workflow.py

Updated #266 with a test - thx @bluegenes !!

Fix `extract_nodes_by_shadow_ratio` and add test

---

spacegraphcats/conf/Snakefile

Fixes #260 and #224, I think.
@taylorreiter lmk!

give better output for BCALM-not-installed vs BCALM-has-error

---

spacegraphcats/catlas/catlas.py

If (for whatever reason) the catlas is empty, exit and provide an error message.
Comes with test files!
Addresses #259.

[WIP] add better error message & early exit for empty catlas

---

doc/installing-spacegraphcats.md

fix install docs for dory test output
