- .coveragerc
- spacegraphcats/test_cmd_line.py
At some point in @microgravitas refactoring of catlas stuff, `search-catlas-mh.py` behavior changed -- see test breakage [on drone run 82](https://drone.io/github.com/spacegraphcats/spacegraphcats/82).  The output on the tr-cross synthetic data set changed to
```
tr-1.fa.sig.dump.txt,0.488,0.976,0,0
```
from
```
tr-1.fa.sig.dump.txt,0.488,0.976,0,1
```
Digging in a little, it seems that the output of build-catlas.py changed here, rather than the search script. Is this shift in behavior expected?
> updated new catlas test to pass

- dump_catlas.py
- requirements.txt
- search-catlas-mh.py
- search-dbg.py
- search-for-domgraph-nodes-multi.py
- search-for-domgraph-nodes.py
- spacegraphcats/catlas.py
- spacegraphcats/color-domgraph.py
- spacegraphcats/graph.py
- spacegraphcats/search-catlas-levels.py
- walk-dbg.py
The shifts the dependency on khmer.MinHash (which is not in the master branch of khmer) over to the sourmash MinHash implementation.  Since all of the other necessary functionality for spacegraphcats is in the main branch of khmer, this reduces the maintenance burden on both projects but does introduce another dependency.
> switch to using master branch of khmer + sourmash library

- build-catlas.py
- merge-mxt-in-memory.py
- merge-mxt-on-disk.py
- spacegraphcats/catlas.py
- spacegraphcats/test_cmd_line.py
The majority of memory usage during catlas construction seems to be coming from keeping the MinHashes in memory. This PR provides an option that turns off MinHash loading and computation in `build-catlas.py`, and further provides `merge-mxt-on-disk.py`, a slower but more memory efficient merge script that uses an on-disk sqlite3 database, and `merge-mxt-in-memory.py`, a faster but still more memory-efficient merge script that works in RAM.
Results on the ~100m read Podar data set, which has 1882162 vertices, 2021493 edges and 30711 components:
* `build-catlas.py XXX 5` requires > 15 GB of RAM (as in, doesn't complete on a 15 GB machine).
* `build-catlas.py --no-merge-mxt XXX 5` requires about 6 GB of RAM.
* `merge-mxt-on-disk.py XXX 5` requires < 1 GB of RAM.
Also note that building the …
> Optionally remove MXT merging from build-catlas.py

- doc/graph-classification-by-minhash.md
As requested, I have edited the description of the frontier search to accurately describe the changes we've made since realizing the Jaccard similarity was computed incorrectly.
> updates on how the frontier search works

- Makefile
- spacegraphcats/rdomset.py
It became clear this week that "real" read data sets seem to introduce interesting new features into the cDBG - podar causes many more problems with components and minhashes than acido or 15genome, neither of which use real reads.
This PR introduces a new data set which is a subset of the reads in podar, obtained by mapping the reads from podar against a specific genome sequence.  The read data set is too big to store in github, so I put it in [our OSF project](https://osf.io/6rgzj/) and added a Makefile rule to download it; see target `shewanella.abundtrim.gz` in Makefile.
> Add a more manageable "real read" data set for testing - the shewanella reads

- spacegraphcats/rdomset.py
This changes the catlases, but it makes them correct.  Addresses the issues in #97 in a way that works on `podar` and `hu_subset`.
> Re-add bidirectional edges in graph in order to correctly compute the domination graph edges

- Makefile
Rebuilt the podar catlas and updated the OSF version to podar-2017.05.06b.tar.gz after merge of #118. Much smaller! Faster! Yay!
Merge when ready.
```
% time python -m search.frontier_search data/mircea-sigs/mircea-rm18.0.fa.sig podar 0.1 --purgatory
loaded 5320993 nodes from catlas podar/catlas.csv
loaded query sig Acidobacterium_capsulatum_ATCC_51196
Root containment: 0.627039627039627
Root similarity: 0.015648632926119836
Containment of frontier: 0.627039627039627
Similarity of frontier: 0.6241299303944315
Size of frontier: 420384 of 5320993 (7.9%)
Overhead of frontier: 0.007380073800738007
Number of leaves in the frontier: 4
Number of empty catlas nodes in the frontier: 420112
Size of the shadow: 1232621
41.58 real        36.61 user         1.96 sys
```
> update the podar catlas

- .travis.yml
- Makefile
- spacegraphcats/walk_dbg.py
Adjusts `dory-test` target to include building/loading a nodegraph, and adds `dory-test` to the Travis CI.
Fixes #154.
> [MRG] add loading a nodegraph to dory-test target in Makefile

- search/catlas_info.py
- search/extract_contigs_by_frontier.py
- search/extract_reads_by_frontier.py
- search/frontier_search_batch.py
Example output:
```
% python -m search.catlas_info twofoo -k 31
loaded 26041 nodes and 11 layers from catlas twofoo/catlas.csv
top catlas node 26040 has 1271 children.
8523 layer 0 catlas nodes, corresponding to 335388 cDBG nodes.
top node minhash has 10165 mins, k=31 scaled=1000
=> ~1.0165e+07 31-mers total.
581 empty child nodes (of 1271) beneath top node
```
I think some additional useful output might be:
* shadow size of each of the (top_level-1) nodes
* component size distribution (should be approximated by above, no?)
> [MRG] Add 'search.catlas_info' to display some basic stats about catlases.

- search/make_catlas_minhashes.py
- spacegraphcats/catlas.py
- spacegraphcats/graph.py
- spacegraphcats/rdomset.py
This fixes #143 by letting level 1 be the leaves rather than level 0.  It also does not propagate up the CAtlas nodes corresponding to components that are simply isolated vertices.  Instead, once a vertex becomes isolated in the domgraph, its corresponding CAtlas node immediately becomes a child of the root.
> CAtlas indexing and isolate removal

- Makefile
Another approach to address https://github.com/TheoryInPractice/cats-in-practice/issues/17.
Briefly, the idea is that we calculate multiple minhash databases with different seeds (independent of the k-mer size) and then search at each of those different seeds.  For now, there is a new search routine, `search.extract_reads`, which takes as input query *sequences* rather than query *signatures* - this is because there is ~poor support in sourmash for saving and loading signatures with multiple seeds.
My proposed workflow is:
* calculate minhash DBs for multiple seeds
* search & extract matches using `search.extract_reads`, avoiding seed=42 which is the default MinHash seed;
* calculate containment and similarity of the extracted reads at seed=42.
If so, merge with care as this will require …
> [MRG] enable minhash searches with different seeds

- search/extract_nodes_by_query.py
Previously, when outputting each *.contigs.sig file from search, we set the signature name to the filename of the signature itself (which is not very useful). Now set it to `nbhd:` plus the first FASTA header in the query file; this preserves accession information that can be used to get taxonomy, etc.
> [MRG] Add query name to contigs signature output by extract_nodes_by_query

- conf/Snakefile
- conf/podarV-noise.json
- conf/twofoo-noise.json
- search/bcalm_to_gxt.py
`bcalm_to_gxt.py` now removes pendant vertices with abundance 1 by default; this behavior can be revoked with the `-P` flag.
> [MRG] Trim low abundance

- requirements.txt
- spacegraphcats/catlas/graph.py
- spacegraphcats/catlas/rdomset.py
We still have non-determinism inside the graph data structure, but this one point is where I suspect results might change substantially depending on iteration order. If this does not help to normalize results we need to introduce ordered sets in graph.py.
> Determ. iteration in domination_graph

- spacegraphcats/search/extract_nodes_by_query.py
In the _Mus musculus_ refseq txome, there are some contigs <30bp in length, which break "search" with cdbg of ksize = 31. Here's a fix that ignores any contigs smaller than ksize.
Don't think this happens _too_ often. Here are the only two offending contigs in the refseq txome (GRCm38):
```
>NR_028434.1 Mus musculus snoRNA AF357359 (AF357359), small nucleolar RNA
ATCATGACGACAAATTTAATTCTGAGATCA
>NR_028557.1 Mus musculus small nucleolar RNA, C/D box 98 (Snord98), small nucleolar RNA
AATGCAGTGTGGAACATAATGAACTGAA
```
> ignore seqs shorter than ksize in search

- conf/Snakefile
This was an issue for running the extract_reads workflow. {catlas_dir} was evaluated as a snakemake wildcard, instead of the value defined at the top of the Snakefile. 
2nd minor change: label_reads rule did not need the `contigs.fa.gz` file as input.
> do not allow defined vars to act as snakemake wildcards

- spacegraphcats/conf/Snakefile
Fixes https://github.com/spacegraphcats/spacegraphcats/pull/214#issuecomment-449219563 thx @charlesreid1!
Output is now:
```
...
(bbcalm -in bcalm.dory.k21.inputlist.txt -out dory/bcalm.dory.k21 -kmer-size 21 
-abundance-min 1 >& dory/bcalm.dory.k21.unitigs.fa.log.txt && rm -f dory/bcalm.d
ory.k21.{h5,unitigs.fa.glue*}) || printf '**\n**\n** Cannot run BCALM 2! Please 
install it and make sure it is on your path!\n**\n**\n'
**
**
** Cannot run BCALM 2! Please install it and make sure it is on your path!
**
**
Waiting at most 3 seconds for missing files.
...
```
> [MRG] provide a nicer error message when bcalm fails to run

- spacegraphcats/conf/Snakefile
rule hashval_query was missing the input file for 'catlas.csv', causing the rule to break from missing file. See comments on #233
> add dependency for rule hashval_query

- requirements.txt
Updates snakemake version to 5.6.0 instead of allowing unrestricted version. With the snakemake bump to 5.7.0, f strings were introduced which causes builds to fail for python 3.5. The internal API must have also changed, because the spacegraphcats config file was no longer being handled properly. Addresses errors in #244 and build fails in #246 and #245.
> update requirements.txt to specify snakemake version 5.6.0

- requirements.txt
- spacegraphcats/__main__.py
Adds `--unlock` parameter to the command line to allow [unlock of snakemake processes](https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-does-snakemake-lock-the-working-directory). Addresses #221. 
Note this still needs to be tested before merge, as spacegraphcats installations were failing from master when I added this.
> [MRG] add unlock to command line

- requirements.txt
- spacegraphcats/__main__.py
- spacegraphcats/cdbg/bcalm_to_gxt.py
- spacegraphcats/conf/Snakefile
Usage: `python -m spacegraphcats dory-test search extract_reads extract_contigs --outdir=/tmp`
This will put all of the output files under /tmp/.
Fixes #223.
> Add --outdir to spacegraphcats command line

- spacegraphcats/search/query_by_sequence.py
- spacegraphcats/search/test_workflow.py
Fixes #263 
After running 
```
% make dory-test
% sourmash sig describe dory_k21_r1_search_oh0/*.sig
```
we now see:
```
...
signature filename: dory_k21_r1_search_oh0//dory-head.fa.contigs.sig
signature: nbhd:TRINITY_DN290219_c0_g1_i1 len=854 path=[1764:0-36 1765:37-60 1767:61-545 1762:546-569 1763:570-853] [-1, 1764, 1765, 1767, 1762, 1763, -2] from dory_k21_r1
...
signature: nbhd:nomatch from dory_k21_r1
source file: random-query-nomatch.fa.contigs.sig
```
> add the catlas name to the output signature name

- Makefile
- environment.yml
To generate problem with this branch:
```
git clone https://github.com/spacegraphcats/spacegraphcats/ -b mac_bcalm_problem
conda env create -f spacegraphcats/environment.yml -n sgc-broke2
conda activate sgc-broke2
cd spacegraphcats
make twofoo-test
```
This will generate the following error:
```
File "/private/tmp/sgc-broke2/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt.py", line 215, in read_bcalm
assert not fail
AssertionError
[Tue Jul 21 06:42:06 2020]
Error in rule bcalm_catlas_input:
jobid: 3
output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
shell:
/Users/t/miniconda3/envs/sgc-broke2/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
(one of the …
```
> demonstrate mac os x problem w/bcalm
